### ISSUE TITLE
RFC: `Show` for types which shouldn't be shown

### ISSUE THREAD

**Issue by olorin** [ambiata/zodiac#73]
This has come up in discussions a few times, putting this up as a venue to work out how to deal with this/similar questions.

When writing types for secret data (keys et cetera) I have an aversion to deriving `Show` instances for them, basically because I'm paranoid and I don't want to make it easy for someone to slip up and include the data in a debug log or something by calling `show` on some higher-level type (e.g., `RunningConfig` containing a `SecretKey` or something). This is fine as we don't use `Show` for anything, except when it comes to tests - e.g., `forAll` and `===` in quickcheck both need a `Show`. This can be worked around (e.g., `Blind`), but it's ugly and inconvenient when you're testing things like parsers where you really want to see what failed to parse.

We have a few ways of dealing with this:

 - Add orphan `Show` instances to the test package for the secret types so they can be used for tests and to derive `Show` instances for larger types in other packages' testsuites. For example, if package `foo` exports `SecretKey` and `foo-test` exports the orphan `Show` for `SecretKey`, then if `bar` defines `RunningConfig = RunningConfig SecretKey [ ... ]` `bar-test` can import `foo-test` and have `deriving instance Show RunningConfig`. This is what I've been doing so far, but @charleso has raised concerns about the use of orphans.

 - Derive `Show` instances for the secret types and trust people to use them sensibly (i.e., not at all in non-test code).

 - Implement a `Show` instance which discards the secret, e.g., `instance Show SecretKey where show _ = "<redacted Foo.SecretKey>"`. This allows us to avoid orphans, but breaks `read . show = id`. I'm okay with this as it's not a real law anyway but others may feel differently.

 - Rewite tests to not rely on `Show`. This seems like a good solution to me, but requires reimplementing a lot of stuff.

Thoughts? Am I missing any potential solutions here?

@charleso @erikd-ambiata @jystic + anyone else who's interested

**Comment by jystic** [comment]
I didn't realise this was an option:
>  - Implement a `Show` instance which discards the secret, e.g., `instance Show SecretKey where show _ = "<redacted Foo.SecretKey>"`. This allows us to avoid orphans, but breaks `read . show = id`. I'm okay with this as it's not a real law anyway but others may feel differently.

The only thing that really matters (to me) for `Show` instances is that they're made of valid Haskell 98 tokens, so as long as show for SecretKey is something like `SecretKey Redacted` (as opposed to `<redacted Foo.SecretKey>`) then I'd be ok with it.

If you pasted that in to your editor you'd get something like "unknown constructor `Redacted`" and it would all be pretty sensible I think?

**Comment by olorin** [comment]
> If you pasted that in to your editor you'd get something like "unknown constructor Redacted" and it would all be pretty sensible I think?

That sounds reasonable to me, I'd be happy with `SecretKey Redacted`.

**Comment by nhibberd** [comment]
Yeah would prefer not to have the orphans at all. I think it would be better to either derive the `Show` instances or rewrite the tests, but im also ok with the other solution that jacob expanded on

**Comment by charleso** [comment]
Obviously 👍  for no orphans, Jacob's suggestion seems fine to me

**Comment by olorin** [comment]
Cool, I will go with redacted instances. Thanks for comments everyone. :+1:

**Comment by damncabbage** [comment]
I'd take Jacob's redacted Show first, or failing that test rewriting, or failing that orphaned Show. I'd never want to take the derived option for this.

**Comment by thumphries** [comment]
This ship has sailed, but I wish we'd put a WARNING pragma on `show` in P. It's something we usually lint out during review. non-derived Show gets quite annoying, you can't paste your QuickCheck counterexamples into GHCi etc.

**Comment by charleso** [comment]
> This ship has sailed, but I wish we'd put a WARNING pragma on show in P. It's something we usually lint out during review. non-derived Show gets quite annoying, you can't paste your QuickCheck counterexamples into GHCi etc.

💯  but compatibility would be quite painful :(

**Comment by olorin** [comment]
> WARNING pragma on show in P

You mean not call `show` anywhere in any of our codebases? That sounds great to me, it's basically what needs to happen for the "reimplement the tests" option here (mostly in disorder et cetera).

**Comment by jystic** [comment]
>> WARNING pragma on show in P

> You mean not call `show` anywhere in any of our codebases? That sounds great to me, it's basically what needs to happen for the "reimplement the tests" option here (mostly in disorder et cetera).

It would be easy to have a version of `forAll` which takes a render function, but I think for the most part you *do* want to use `Show` so that you can paste your counterexample. I agree we shouldn't be using it in most of our other code though.
