### ISSUE TITLE
Check canonicalisation of empty path

### ISSUE THREAD

**Issue by olorin** [ambiata/zodiac#97]
Verify behaviour for `""` vs `"/"`.

**Comment by olorin** [comment]
My initial [reading](https://tools.ietf.org/html/rfc3986#section-3.3) is that they should be treated differently - `""` is a zero-segment-long path, `"/"` is a one-segment-long path. Will think about this more.

**Comment by markhibberd** [comment]
The AWS V4 spec handles it explicitly, it says the empty path should be replaced by / during canonicalisation.

**Comment by olorin** [comment]
> The AWS V4 spec handles it explicitly, it says the empty path should be replaced by / during canonicalisation.

Yeah I think this is the way to go here too, it doesn't make sense to differentiate them in the context of the HTTP protocol.

**Comment by olorin** [comment]
> > The AWS V4 spec handles it explicitly, it says the empty path should be replaced by / during canonicalisation.

> Yeah I think this is the way to go here too, it doesn't make sense to differentiate them in the context of the HTTP protocol.

Got rid of ambiguity in spec (#98) and implemented new behaviour in `zodiac-http-client` (#99).
